### ISSUE TITLE
Stuck at node test/integration/e2e/create-channel.js

### ISSUE THREAD

**Issue by roysoham** [IBM/todo-list-fabricV1#14]
Hello 

Have setup till create-channel.js and getting the below error, tried re-installing till this step and unable to find any solution for the below error.
This class requires a CryptoKeyStore to save keys, using the store: {"opts":{"path":"/root/.hfc-key-store"}}
not ok 1 Error: Could not parse enrollment response [{"success":false,"result":null,"errors":[{"code":0,"message":"open /etc/hyperledger/fabric-ca-server-cog/peerOrg1-cert.pem: no such file or directory"}],"messages":[]} ] as JSON due to error [TypeError: Cannot read property 'errors' of undefined] at IncomingMage.<anonymous> (/root/todo-list-fabricV1/fabric-sdk-node/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:560:14) at emitNone (events.js:91:20) at ImingMessage.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:74:11) at process._kCallback (internal/process/next_tick.js:98:9)
  ---
    operator: fail
    at: cop.enroll.then.then.then.catch (/root/todo-list-fabricV1/fabric-sdk-node/test/unit/util.js:119:8)
    stack: |-

**Comment by bigfanxx** [comment]
Same question，have you solved it?
