### ISSUE TITLE
hashtable@2.0.2 install: `node-gyp configure build`

### ISSUE THREAD

**Issue by Zmhan-github** [IBM/todo-list-fabricV1#16]
I followed the instructions at the command input stage:

> node test / integration / e2e / join-channel.js

info: Returning a new winston logger with default configurations
module.js: 471
    throw err;
    ^

Error: Can not find module 'hashtable'
    at Function.Module._resolveFilename (module.js: 469: 15)
....

Then I tried to install the hashtable

> npm install hashtable 

> hashtable@2.0.2 install /root/todo-list-fabricV1/fabric-sdk-node/node_modules/hashtable
> node-gyp configure build

make: Entering directory '/root/todo-list-fabricV1/fabric-sdk-node/node_modules/hashtable/build'
  CXX(target) Release/obj.target/native/src/hashtable.o
make: g++: Command not found
native.target.mk:98: recipe for target 'Release/obj.target/native/src/hashtable.o' failed
make: *** [Release/obj.target/native/src/hashtable.o] Error 127
make: Leaving directory '/root/todo-list-fabricV1/fabric-sdk-node/node_modules/hashtable/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command "/root/.nvm/versions/node/v6.9.5/bin/node" "/root/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /root/todo-list-fabricV1/fabric-sdk-node/node_modules/hashtable
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/root/.nvm/versions/node/v6.9.5/bin/node" "/root/.nvm/versions/node/v6.9.5/bin/npm" "install" "hashtable"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! hashtable@2.0.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashtable@2.0.2 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hashtable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hashtable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hashtable
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/todo-list-fabricV1/fabric-sdk-node/npm-debug.log

my mistake

**Comment by Zmhan-github** [comment]
I solved the problem by creating a new user

**Comment by agentidea** [comment]
I found that g++ was not installed on CentOS7 
solved this by installing g++

`sudo yum install gcc-c++`
