### ISSUE TITLE
Fail to create a channel

### ISSUE THREAD

**Issue by Jaraxuss** [IBM/todo-list-fabricV1#21]
After ```node test/integration/e2e/create-channel.js```, I got the following message:

```
info: Returning a new winston logger with default configurations
TAP version 13
#

***** End-to-end flow: create channel *****


info: [Client.js]: Failed to load user "admin" from local key value store
info: [FabricCAClientImpl.js]: Successfully constructed Fabric CA client from options - {"protocol":"http","hostname":"localhost","port":7054}
info: [FabricCAClientImpl.js]: Successfully constructed Fabric CA service client: endpoint - {"protocol":"http","hostname":"localhost","port":7054}
info: [crypto_ecdsa_aes]: This class requires a CryptoKeyStore to save keys, using the store: {"opts":{"path":"/Users/velen/.hfc-key-store"}}
not ok 1 Error: Could not parse enrollment response [404 page not found ] as JSON due to error [SyntaxError: Unexpected token pin JSON at position 4] at IncomingMessage.<anonymous> (/Users/velen/Desktop/blockChain/todo-app/fabric-sdk-node/node_modules/_fabric-ca-client@1.0.0-alpha@fabric-ca-client/lib/FabricCAClientImpl.js:560:14) at emitNone (events.js:91:20) at IncomingMessage.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:74:11) at process._tickCallback (internal/process/next_tick.js:98:9)
  ---
    operator: fail
    at: cop.enroll.then.then.then.catch (/Users/velen/Desktop/blockChain/todo-app/fabric-sdk-node/test/unit/util.js:119:8)
    stack: |-
      Error: Error: Could not parse enrollment response [404 page not found
      ] as JSON due to error [SyntaxError: Unexpected token p in JSON at position 4]
          at IncomingMessage.<anonymous> (/Users/velen/Desktop/blockChain/todo-app/fabric-sdk-node/node_modules/_fabric-ca-client@1.0.0-alpha@fabric-ca-client/lib/FabricCAClientImpl.js:560:14)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickCallback (internal/process/next_tick.js:98:9)
          at Test.assert [as _assert] (/Users/velen/Desktop/blockChain/todo-app/fabric-sdk-node/node_modules/_tape@4.9.0@tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/velen/Desktop/blockChain/todo-app/fabric-sdk-node/node_modules/_tape@4.9.0@tape/lib/test.js:77:32)
          at Test.fail (/Users/velen/Desktop/blockChain/todo-app/fabric-sdk-node/node_modules/_tape@4.9.0@tape/lib/test.js:318:10)
          at Test.bound [as fail] (/Users/velen/Desktop/blockChain/todo-app/fabric-sdk-node/node_modules/_tape@4.9.0@tape/lib/test.js:77:32)
          at cop.enroll.then.then.then.catch (/Users/velen/Desktop/blockChain/todo-app/fabric-sdk-node/test/unit/util.js:119:8)
          at process._tickCallback (internal/process/next_tick.js:103:7)
  ...

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by ajaya-man** [comment]
How did you solve this issue ?
