### ISSUE TITLE
5. Run the todo list fabric server

### ISSUE THREAD

**Issue by Gxz-NGU** [IBM/todo-list-fabricV1#27]
Run the server:

`node server.js`

when I run this, I got a problem.
```
[root@localhost todo-list-fabric-server]# node server.js
info: Loaded config file /usr/local/dockerImages/todo-list-fabricV1-master/todo-list-fabric-server/config/toodles_data.json
info: Loaded creds file /usr/local/dockerImages/todo-list-fabricV1-master/todo-list-fabric-server/config/blockchain_creds.json
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/local/dockerImages/todo-list-fabricV1-master/todo-list-fabric-server/node_modules/grpc/src/node/extension_binary/grpc_node.node: ELF load command past end of file
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/dockerImages/todo-list-fabricV1-master/todo-list-fabric-server/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

can someone help me? 

> ELF load command past end of file

what does this mean? How can I trace it?

**Comment by Gxz-NGU** [comment]
Just a few minutes ago I just solved this problem. I found that the dependencies of node.js are wrong. I need to download the complete dependencies from the correct website. Especially developers from China need to pay attention, grpc's 1.1.2 dependency package does not seem to be on Taobao source.
So just make **npm install** be correct!
