### ISSUE TITLE
create channel issue

### ISSUE THREAD

**Issue by shankarjai2525** [IBM/todo-list-fabricV1#28]
I'm running into an issue when i run this command
node test/integration/e2e/create-channel.js

node version : v8.12.0
npm version : 6.4.1

module.js:550
    throw err;
    ^

Error: Cannot find module '/Users/jgothan@us.ibm.com/Client/BlockChain/todo-list-fabricV1/fabric-sdk-node/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jgothan@us.ibm.com/Client/BlockChain/todo-list-fabricV1/fabric-sdk-node/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by ajaya-man** [comment]
Did you try this step?
Go back to the root of the fabric-sdk-node directory and add grpc dependency `"grpc": "1.1.2"` to package.json
