### ISSUE TITLE
can't login todo application

### ISSUE THREAD

**Issue by kkyouhei** [IBM/todo-list-fabricV1#9]
Hi

I setup according to README but can't login todo application.

![2017-11-11 22 44 19](https://user-images.githubusercontent.com/300724/32690009-5a2bd31e-c732-11e7-973c-3ca3afdab52b.png)

```server.js
~/D/d/t/todo-list-fabric-server ❯❯❯ node server.js
info: Loaded config file /Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/config/toodles_data.json
info: Loaded creds file /Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/config/blockchain_creds.json
info: Returning a new winston logger with default configurations
------------------------------------------ Server Up - localhost:3000 ------------------------------------------
debug: Query parameters : [object Object]

info: Fetching EVERYTHING...
debug: [fcw] Querying Chaincode: account_read()
TypeError: Cannot read property 'chain' of null
    at Object.query_cc.query_chaincode (/Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/utils/fc_wrangler/query_cc.js:23:18)
    at Object.fcw.query_chaincode (/Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/utils/fc_wrangler/index.js:34:12)
    at Object.toodles_chaincode.query_function (/Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/utils/toodles_cc_lib.js:37:7)
    at /Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/server.js:127:15
    at Layer.handle [as handle_request] (/Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/kkyouhei/Developer/docker/todo-list-fabricV1/todo-list-fabric-server/node_modules/express/lib/router/index.js:335:12)
```

I saw inside couchDB
![2017-11-11 22 53 22](https://user-images.githubusercontent.com/300724/32690045-29d938d6-c733-11e7-8984-2b5a3f388f3b.png)

Is there a mistake in the procedure I did?

**Comment by ishangulhane** [comment]
@kkyouhei : You need to load the data into the blockchain. Alt+Click on IBM logo to preload data . The only indication that this operation has been completed is a transaction ID in the developer console.

**Comment by kkyouhei** [comment]
@ishangulhane thank you so much 🤗
